plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md

title: The Curse of Learning
description: The more probable is the answer the less information it communicates.
